-- BliGO — Fiche complète pour la Sélection BliGO de septembre (15/09/2026)
-- Résumé, format, éditeur, date de publication, nombre de pages, langue,
-- récupérés via Google Books (Open Library en appoint pour le format).
-- Chaque résumé vérifié un par un : 1 retiré (encodage cassé côté Google Books).
--
-- Prérequis : sql/add_curated_lists_full_record.sql
-- À exécuter dans Supabase : Project > SQL Editor > New query > coller > Run

-- La Prof
update public.monthly_top_books set summary = 'Dans les couloirs d’un lycée en apparence ordinaire, les silences pèsent plus lourd que les mots. Une enseignante prisonnière d’un mariage aux failles invisibles, une adolescente rejetée par tous depuis un scandale qui continue de la poursuivre, un professeur admiré dont la bienveillance cache peut-être d’autres vérités… Chacun avance avec ses blessures, ses mensonges et ses obsessions, jusqu’au jour où les frontières entre innocence et culpabilité se brouillent. Dans cette mécanique implacable où chaque regard peut condamner et chaque secret devenir une arme, les certitudes s’effondrent une à une, laissant place à une vérité aussi inattendue que vertigineuse.', publisher = '-', page_count = '318', language = 'fr' where month = '2026-09-01' and rank = 1;

-- Les Belles Promesses
update public.monthly_top_books set summary = 'Tout commence par un incendie, un bébé... et un sanglier. Paris est transformé par des travaux titanesques, le cœur d’un homme est écartelé, le monde rural menacé, des femmes sortent de l’oubli, et les membres de la famille Pelletier, toujours plus proches de nous, marchent inexorablement vers leur destin. Au terme d’un effroyable dilemme moral, ce sera l’effondrement ou l’apothéose. Par bonheur, le chat Joseph veille encore. Passionnant, déchirant, enthousiasmant. Un grand roman de Pierre Lemaitre. Les romans de Pierre Lemaitre ont été récompensés par de nombreux prix littéraires nationaux et internationaux. Après l’immense succès du Grand Monde, du Silence et la Colère, et d’Un avenir radieux, il clôt avec Les Belles Promesses sa plongée mouvementée et jubilatoire dans les Trente Glorieuses.', publisher = 'Calmann-Lévy', published_date = '2026-01-06', page_count = '458', language = 'fr' where month = '2026-09-01' and rank = 2;

-- La femme de ménage
update public.monthly_top_books set summary = 'Chaque jour, Millie fait le ménage dans la belle maison des Winchester, une riche famille new-yorkaise. Elle récupère aussi leur fille à l''école et prépare les repas avant d''aller se coucher dans sa chambre, au grenier. Pour la jeune femme, ce nouveau travail est une chance inespérée. L''occasion de repartir de zéro. Mais, sous des dehors respectables, sa patronne se montre de plus en plus instable et toxique. Et puis il y a aussi cette rumeur dérangeante qui court dans le quartier : madame Winchester aurait tenté de noyer sa fille quelques années auparavant. Heureusement, le gentil et séduisant monsieur Winchester est là pour rendre la situation supportable. Mais le danger se tapit parfois sous des apparences trompeuses. Et lorsque Millie découvre que la porte de sa chambre mansardée ne ferme que de l''extérieur, il est peut-être déjà trop tard...', published_date = '2023', language = 'fr' where month = '2026-09-01' and rank = 3;

-- Je suis Romane Monnier
update public.monthly_top_books set published_date = '2026-04-07', language = 'fr' where month = '2026-09-01' and rank = 4;

-- D'autres printemps
update public.monthly_top_books set summary = 'Elles n''imaginent rien de ce qui les attend au bout du chemin, là où l''histoire a commencé. Flora vient de voir son plus grand rêve s''effondrer. Pourtant, quand on l''appelle au chevet de sa grand-mère, elle envoie tout valser pour la retrouver. À son arrivée, Line, quatre-vingt-dix printemps, a une requête des plus surprenantes: Flora doit l''arracher à l''hôpital pour la conduire dans un petit village de Toscane. Pourquoi là-bas? Personne ne lui connaît d''attaches en Italie. Flora hésite, mais Line insiste: c''est sa dernière volonté. Alors, au matin, elles fuguent. Embarquée dans un road trip insolite, Flora ignore la vraie raison de ce voyage et l''ampleur du secret qu''elle s''apprête à découvrir. L''une roule vers son passé, l''autre vers son avenir: grand-mère et petite-fille ont des choses à se dire.', publisher = 'Édito', published_date = '2026-06-10T00:00:00+02:00', page_count = '263', language = 'fr' where month = '2026-09-01' and rank = 5;

-- Le crime du paradis
update public.monthly_top_books set summary = '"Florence et Julian Livingstone, un couple d''Américains fortunés, réunissent chaque été un petit cercle d''amis dans leur somptueuse maison du cap d''Antibes. Mais ce monde idyllique s''effondre la nuit où Oscar, leur fils de trois ans, est enlevé dans des conditions mystérieuses. Alors que l''affaire passionne le monde entier et que la peur se répand, le policier chargé de l''enquête se heurte à un mur de mensonges et de secrets. Son chemin va croiser celui de la jeune romancière Agatha Harding qui espère s''emparer du drame pour écrire un best-seller..."--Publisher''s website.', published_date = '2026-03-03', language = 'fr' where month = '2026-09-01' and rank = 6;

-- La psy
update public.monthly_top_books set summary = 'Jeunes mariés, Tricia et Ethan recherchent la maison de leurs rêves. Alors qu''ils visitent un manoir isolé ayant appartenu au docteur Adrienne Hale, une psychiatre renommée disparue sans laisser de trace quatre ans plus tôt, une violente tempête de neige les piège sur place. Et la maison n''a rien d''un cocon rassurant... Il y a ces empreintes de pas récentes sur le parquet, ces bruits à l''étage, comme si quelqu''un vivait là. Pire encore : Tricia découvre une pièce secrète qui renferme les enregistrements audio de chaque patient du docteur Hale. La jeune femme les écoute les uns après les autres, tard dans la nuit. La toile de mensonges ayant conduit à la disparition de la psy se dévoile lentement. Mais déterrer de vilains petits secrets est un jeu dangereux, et lorsque Tricia écoute le dernier enregistrement, il est déjà trop tard..[4 ème de couverture]', published_date = '2024-04-17', language = 'fr' where month = '2026-09-01' and rank = 7;

-- Mortelle Adèle Tome 23
update public.monthly_top_books set summary = 'L''héroïne N°1 de la bande dessinée jeunesse revient dans un 23e tome de gags toujours aussi attendu du public ! Plus de 70 gags pleins d''énergie et de réflexions sur le quotidien, comme Antoine Dole alias Mr Tan en a le secret, et toujours illustrée par la talentueuse Diane Le Feyer ! © Mr Tan et Diane Le Feyer d''après l''œuvre créée par Mr Tan et Miss Prickly © Mr Tan & Co', publisher = 'Mr Tan Company', published_date = '2026-05-28', page_count = '80', language = 'fr' where month = '2026-09-01' and rank = 8;

-- L'autre moi
update public.monthly_top_books set published_date = '2026-04-28', language = 'fr' where month = '2026-09-01' and rank = 9;

-- Fauves
update public.monthly_top_books set summary = '« Je veux jouer avec le feu, trembler, sentir la morsure de la mort. Défier les instincts les plus brutaux, les plus sauvages, et les dépasser. » Comment s''échapper de sa cage ? C''est l''obsession des fauves mais aussi celle de Tony, dix-sept ans, lorsqu''il rejoint un cirque itinérant après avoir fui la violence de son père. Faire face aux bêtes, affronter ses propres démons... Le nouveau roman de Mélissa Da Costa nous propulse au coeur de l''arène, où l''ivresse du danger fait oublier la mort. Une fresque magistrale, portée par une écriture tendue et charnelle.', publisher = 'Albin Michel', published_date = '2026-01-07', page_count = '427', language = 'fr' where month = '2026-09-01' and rank = 10;

-- La femme de ménage voit tout
update public.monthly_top_books set summary = '« Je me demande si je n''ai pas commis une terrible erreur en m''installant ici... » . Après avoir été au service des autres en tant que femme de ménage, Millie s''est enfin construit une vie à elle. Elle vient même d''emménager dans une belle maison, dans une petite impasse chic et tranquille, avec son mari et ses deux enfants.. Mais son rêve d''une vie paisible est rapidement terni par la rencontre de ses voisins. Il y a Suzette, bien trop snob et aguicheuse, son insipide mari, mais surtout leur terrifiante femme de ménage au regard perçant et au comportement plus que suspect.. Les craintes de Millie montent d''un cran lorsque des bruits étranges se font entendre la nuit dans sa propre maison. Pire : elle éprouve un étrange malaise et se sent épiée. C''est certain, quelque chose ne tourne pas rond dans cette rue si tranquille. Mais est-elle prête à en découvrir les secrets ? Et surtout, le temps de comprendre ce qui ne va pas, tout peut arriver.... Elle vous observe. Et vous n''avez nulle part où vous cacher. .', published_date = '2024-10-02', language = 'fr' where month = '2026-09-01' and rank = 11;

-- Que la mort nous frôle
update public.monthly_top_books set summary = 'Avec Que la mort nous frôle, Michel Bussi revient à l''essence de son art : un suspense psychologique haletant, un huis clos oppressant et une intrigue savamment orchestrée, où rien n''est jamais ce qu''il paraît être. Quand on frôle la mort, ce n''est pas son passé que l''on voit défiler. Ce sont les rêves que l''on ne pourra pas réaliser. Près de Lausanne, Jeanne, jeune psychiatre spécialisée dans les traumatismes, rejoint le manoir des Amarantes, qui, depuis 1945, abrite des pensionnaires brisés par la guerre. Parmi eux, Charly, adolescent imprévisible et paranoïaque, et Téréza, orpheline du ghetto de Varsovie, ont noué un lien très fort. Mais ces dernières semaines, des événements inquiétants secouent les lieux : des pensionnaires disparaissent, de mort naturelle prétend-on ; des statues changent de place ; le docteur Gruber, directeur de l''établissement, mène des expériences mystérieuses. Tandis que les ombres et les non-dits pèsent sur ce manoir hors du temps, le danger est partout. Derrière un décor faussement paisible, entre les rives du Léman et les sommets alpins, le passé peut-il encore tuer ? Avec Que la mort nous frôle, Michel Bussi signe un suspense psychologique haletant, où chaque révélation renverse tout ce que l''on croyait savoir, jusqu''au twist final. Maître dans l''illusion et l''art de la manipulation, Michel Bussi est l''un des auteurs préférés des Français, et le plus adapté à la télévision et en bandes dessinées.', publisher = 'Presses de la Cité', published_date = '2026-04-16', page_count = '378', language = 'fr' where month = '2026-09-01' and rank = 12;

-- Le visage de la nuit
update public.monthly_top_books set summary = 'À Fond du Puits, à la suite d’une fièvre sévère et de l’intervention d’un guérisseur, un enfant paie sa guérison d’un visage défiguré. Abandonné par son père, puis recueilli et éduqué par le prêtre du village, il devient un être intelligent qui trouve sa liberté dans la forêt, la nuit. Alors qu''il entre dans l''adolescence, une jeune fille apparaît parmi les arbres. Elle ne ressemble en rien aux habitants de ce village perdu. Mais elle aussi porte un secret et rêve d''échapper à l''avenir qui lui est promis. Au fil du temps et des confidences, une relation forte et dangereuse se noue entre les deux jeunes... Un roman éblouissant, traversé d''éclairs sur l''adolescence, la violence et le désir.', publisher = 'Guy Saint-Jean Éditeur', published_date = '2026-04-22T00:00:00-04:00', page_count = '172', language = 'fr' where month = '2026-09-01' and rank = 13;

-- Les Carnets de l'apothicaire Tome 16
update public.monthly_top_books set summary = 'Intrigues et poisons au coeur du palais impérial ! Retenue prisonnière dans les montagnes du nord par la cruelle dame Shenmei, Mao Mao découvre petit à petit la véritable identité de Suilei et de Lolan... De son côté, Jinshi doit répondre à la demande de Lacan, qui le supplie de lever des troupes afin d''écraser la rébellion de Shisho en lieu et place de l''empereur ! En effet, le clan Shi a fabriqué de toutes nouvelles armes en secret et a tenté d''assassiner le bel eunuque... Aussi ce dernier est forcé de prendre ses responsabilités et d''affronter un cruel dilemme : comment protéger la cour sans faire couler le sang ? Découvrez la face cachée du lieu le plus secret de la cité impériale ! Dans ce monde de femmes régi par les hommes, Mao Mao aura besoin de toute son intelligence et de tout son savoir pour démêler les intrigues de la cour... Avec son héroïne hors norme et ses décors magnifiques, ce manga événement adapté d''un roman à succès a tout pour plaire ! Et vous, aurez-vous le courage de goûter à ses délices ?', publisher = 'Ki-oon', published_date = '2026-02-12', page_count = '168', language = 'fr' where month = '2026-09-01' and rank = 14;

-- Ne jamais trembler
update public.monthly_top_books set summary = '« Je vais tuer 13 innocents et 1 coupable. Ainsi, ceux qui ont causé la mort de l''innocent souffriront. Il s''agit d''un acte d''EXPIATION. » Quatorze citoyens dans le viseur d''un prétendu justicier. Signée d''un certain Bill Wilson, la lettre, parvenue à la police de Buckeye City, sème la panique. Surtout lorsqu''il apparaît que le meurtrier choisit ses victimes au hasard. Militante des droits de la femme, Kate McKay vient de se lancer dans une tournée de conférences sulfureuses aux États-Unis. Sans prendre au sérieux les menaces d''un individu qui semble déterminé à la faire taire à tout prix. Au coeur de ces deux affaires, Holly Gibney, le personnage préféré de Stephen King. Palpitant, caustique et scandaleusement captivant, ce roman explore les zones d''ombre de la justice, la colère comme idéologie et la capacité à résister. Il confirme, une fois encore, la maestria d''un écrivain qui n''a jamais cessé d''explorer ce qui nous rend humains et ce qui fait de nous des monstres.', publisher = 'Albin Michel', published_date = '2026-01-28', page_count = '484', language = 'fr' where month = '2026-09-01' and rank = 15;

-- Les secrets de la femme de ménage
update public.monthly_top_books set summary = 'C’est une chance inespérée pour Millie d’avoir décroché un nouveau travail. Chez les Garrick, un couple fortuné qui possède un somptueux appartement avec vue sur New York, elle fait le ménage et prépare les repas dans la magnifique cuisine. Cela paraît trop beau pour être vrai. Et effectivement, la femme de ménage ne tarde pas à déceler quelques ombres au tableau... Son patron, Douglas Garrick, est d’humeur de plus en plus changeante. Et pourquoi sa femme Wendy reste-t-elle toujours enfermée dans la chambre d’amis ? Le jour où Millie découvre du sang sur une chemise de nuit, elle ne peut plus rester les bras croisés. Quelque chose se trame dans cette maison. Une situation à laquelle Millie n’est pas préparée et qui pourrait bien se retourner contre elle si elle continue de vouloir découvrir les secrets des autres...', publisher = 'City Edition', published_date = '2023-10-04', page_count = '364', language = 'fr' where month = '2026-09-01' and rank = 16;

-- La Légende
update public.monthly_top_books set summary = '« Un jour, on découvre que l’on vit dans un monde inversé - où la vérité dérange, où la justice inquiète, où la liberté fait peur. C’est dans ce «pays des miracles » que mon histoire commence. Ou peut-être qu’elle finit. J’ai compris que cette histoire ne m’appartenait pas. Elle circulait sans moi. Elle est née dans la tête du grand magistrat, elle est passée par un tribunal d’exception, par la prison, par les médias des cinq continents, elle s’est chargée des colères et des espoirs des uns et des autres. A aucun moment elle n’est passée par moi. Mon récit me permet de me réapproprier la légende, et rappelle ce qu’est une justice aux ordres, un pouvoir sans contrepoids, la peur quand elle s’installe dans la langue. Les bourreaux prospèrent dans l’anonymat ; la lumière commence par les désigner. Ces pages n’adoucissent rien : elles éclairent... »B.S. La légende n’est pas seulement le récit d’une détention. C’est l’histoire d’un homme que l’on a voulu effacer - et qui devient un symbole.', publisher = 'Grasset', published_date = '2026-06-02', page_count = '198', language = 'fr' where month = '2026-09-01' and rank = 17;

-- Tu m'avais promis
update public.monthly_top_books set summary = 'Et si une promesse pouvait transformer votre destin ? Luce compte les jours depuis trois ans ! Son père, Gabin, lui avait fait la promesse de l’emmener en voyage pour ses huit ans. Malgré ses appréhensions, le quadragénaire sait qu’il doit honorer so', publisher = 'Editions Eyrolles', published_date = '2026-03-12', page_count = '400', language = 'fr' where month = '2026-09-01' and rank = 18;

-- Le barman du Ritz
update public.monthly_top_books set summary = 'Paris, pendant la Seconde Guerre mondiale. Alors que la ville est occupée, un seul palace demeure ouvert, le Ritz qui devient le quartier général de la Luftwaffe. Entre ses murs, se croisent et se côtoient les hommes de la Gestapo, des célébrités, des résistants et des profiteurs de guerre sous le regard acéré de Frank Meier, le barman, émigré autrichien d''origine juive. Premier roman.', published_date = '2024-09-02', language = 'fr' where month = '2026-09-01' and rank = 19;

-- Une pension en Italie
update public.monthly_top_books set summary = 'Retrouvez dans la version numérique d''Une pension en Italie en exclusivité les photos des paysages toscans qui ont inspiré à l''auteur cette histoire bouleversante. Milieu des années 60, en Toscane. Un été caniculaire. Une famille française en villégiature. Un événement inattendu. Des vies qui basculent irrémédiablement. Un secret qui s''impose aussitôt. Un écrivain, héritier de cette histoire, en quête de la vérité. Mêlant suspense et sensualité, Une pension en Italie est un roman solaire sur le prix à payer pour être soi, en écho à Chambre avec vue et Sur la route de Madison.', publisher = 'Julliard', published_date = '2026-01-08', page_count = '155', language = 'fr' where month = '2026-09-01' and rank = 20;

