-- BliGO — Résumés complets pour le catalogue de démo (14/09/2026)
-- Remplace les résumés courts « maison » par le vrai résumé éditeur
-- (Google Books). Demandé explicitement par Mégane, écrase le contenu
-- existant (contrairement aux autres enrichissements du jour).
--
-- Vérifié un par un avant envoi (plusieurs premiers résultats étaient dans
-- la mauvaise langue ou pour le mauvais livre) : ceux ci-dessous sont propres.
--
-- Laissés tels quels (résumé existant conservé, rien de fiable trouvé) :
-- Pluie et vent sur Télumée Miracle, Les Soleils des indépendances,
-- La Porteuse de lettres, Résister, Une si longue lettre,
-- Les Monsieur Madame visitent Fort Boyard, Tant que fleuriront les citronniers.
--
-- À exécuter dans Supabase : Project > SQL Editor > New query > coller > Run

-- Texaco
update public.books set summary = 'L''auteur martiniquais reprend les étapes marquantes de l''histoire de son île "et en constitue la chronique à travers la généalogie d''un personnage" (L. Gauvin). Un roman foisonnant, généreux, incantatoire, somptueux, qui explore "l''inconscient collectif de la culture orale antillaise" (G. Anquetil) et propose un beau portrait de femme créole, sorte de Mère Courage, à la fois mémoire et vestale d''un bidonville greffé sur Fort-de-France. Prix Goncourt 1992' where id = 1;

-- Cahier d'un retour au pays natal
update public.books set summary = '" Et nous sommes debout maintenant, mon pays et moi, les cheveux dans le vent, ma main petite maintenant dans son poing énorme et la force n''est pas en nous, mais au-dessus de nous, dans une voix qui vrille la nuit et l''audience comme la pénétrance d''une guêpe apocalyptique. Et la voix prononce que l''Europe nous a pendant des siècles gavés de mensonges et gonflés de pestilences, car il n''est point vrai que l''œuvre de l''homme est finie, que nous n''avons rien à faire au monde, que nous parasitons le monde mais l''œuvre de l''homme vient seulement de commencer et il reste à l''homme à conquérir toute interdiction immobilisée aux coins de sa ferveur et aucune race ne possède le monopole de la beauté, de l''intelligence, de la force et il est place pour tous au rendez-vous de la conquête et nous savons maintenant que le soleil tourne autour de notre terre éclairant la parcelle qu''a fixée notre volonté seule et que toute étoile chute de ciel en terre à notre commandement sans limite ". La réédition du Cahier d''un retour au pays natal, la première œuvre d''Aimé Césaire, saluée depuis l''origine comme le texte fondamental de la génération de la Négritude.' where id = 4;

-- Ti Jean L'horizon
update public.books set summary = 'Roman-poème. Ti-Jean, héros traditionnel des contes créoles, effectue un "pèlerinage immatériel et concret" vers l''Afrique, son pays d''origine. Sur sa lancée il franchit l''espace-temps et va "jusqu''au Séjour des Morts". A l''origine de son élan, de son exploration dans l''ultérieur et l''antérieur, comme le souligne Guillemin, il y a Egée la "négresse sans fard ni pose". Ecriture rusée et savante, savoureuse par moments comme un fruit de la Guadeloupe.' where id = 5;

-- L'Étranger
update public.books set summary = 'Le roman met en scène un personnage-narrateur nommé Meursault, vivant à Alger en Algérie française. Le roman est découpé en deux parties.Au début de la première partie, Meursault reçoit un télégramme annonçant que sa mère, qu''il a internée à l''hospice de Marengo vient de mourir. Il se rend en autocar à l''asile de vieillards, situé près d''Alger. Veillant la morte toute la nuit, il assiste le lendemain à la mise en bière et aux funérailles, sans avoir l''attitude à attendre d''un fils endeuillé ; le héros ne pleure pas, il ne veut pas simuler un chagrin qu''il ne ressent pas.Le lendemain de l''enterrement, Meursault décide d''aller nager à l''établissement de bains, et y rencontre Marie, une dactylo qui avait travaillé dans la même entreprise que lui. Le soir, ils sortent voir un film de Fernandel au cinéma et passent le restant de la nuit ensemble. Le lendemain matin, son voisin, Raymond Sintès, un proxénète notoire, lui demande de l''aider à écrire une lettre pour dénigrer sa maîtresse, une Maure envers laquelle il s''est montré brutal ; il craint des représailles du frère de celle-ci. La semaine suivante, Raymond frappe et injurie sa maitresse dans son appartement. La police intervient et convoque Raymond au commissariat. Celui-ci utilise Meursault comme témoin de moralité. En sortant, il l''invite, lui et Marie, à déjeuner le dimanche suivant à un cabanon au bord de la mer, qui appartient à un de ses amis, Masson. Lors de la journée, Marie demande à Meursault s''il veut se marier avec elle. Il répond que ça n''a pas d''importance, mais qu''il le veut bien.Le dimanche midi, après un repas bien arrosé, Meursault, Raymond et Masson se promènent sur la plage et croisent deux Arabes, dont le frère de la maîtresse de Raymond. Une bagarre éclate, au cours de laquelle Raymond est blessé au visage d''un coup de couteau. Plus tard, Meursault, seul sur la plage accablée de chaleur et de soleil, rencontre à nouveau l''un des Arabes, qui, à sa vue, sort un couteau. Meursault tire une fois sur l''homme sans raison apparente, puis tire quatre autres coups de feu sur le corps.Dans la seconde moitié du roman, Meursault est arrêté et questionné. Ses propos sincères et naïfs mettent son avocat mal à l''aise. Il ne manifeste aucun regret, mais de l''ennui. Lors du procès, on l''interroge davantage sur son comportement lors de l''enterrement de sa mère que sur le meurtre. Meursault se sent exclu du procès. Il dit avoir commis son acte à cause du soleil, ce qui déclenche l''hilarité de l''audience. La sentence tombe : il est condamné à la guillotine. Meursault voit l''aumônier, mais quand celui-ci lui dit qu''il priera pour lui, il déclenche sa colère.Avant son départ, Meursault finit par trouver la paix dans la sérénité de la nuit.' where id = 7;

-- La Saison de l'ombre
update public.books set summary = '"Au cœur de la brousse subsaharienne, un grand incendie a ravagé les cases du clan Mulongo. Depuis lors, douze hommes manquent à l''appel – les fils aînés pour la plupart. Pendant que les mères cherchent en songe les réponses à leur chagrin, le Conseil interroge les ancêtres, scrute les mystères de l''ombre : que signifie cette disparition ? Pour le salut de la communauté, le chef Mukano et quelques autres décident de partir à leur recherche en territoire bwele, leurs voisins. Peu d''entre eux atteindront l''océan – par où les " hommes aux pieds de poules " emportent leurs enfants..." --Cover.' where id = 8;

-- Le dîner. Une aventure dont vous êtes le héros
update public.books set summary = 'Vous êtes fauchée et vous risquez d’être expulsée de votre appartement. Alors quand une amie vous propose un job de serveuse lors d’un dîner chic dans un manoir totalement isolé, vous croyez rêver. Le salaire pour la soirée ? De quoi couvrir deux mois de loyer et vous remettre sur pied. C’est la chance de votre vie. Pourtant, une petite voix intérieure vous murmure que c’est trop beau pour être vrai. Il y a forcément quelque chose de louche dans l’histoire... Peut-être devriez-vous refuser ? La décision vous appartient. Serez-vous assez prudente pour rester chez vous ? Accepterez-vous de faire monter cet auto-stoppeur étrange sur la route du manoir ? Tournerez-vous à gauche ou à droite à la bifurcation ? Dans ce thriller psychologique interactif, chaque choix vous rapproche de la vérité... et de votre pire cauchemar.' where id = 9;

-- La prof
update public.books set summary = 'Dans les couloirs d’un lycée en apparence ordinaire, les silences pèsent plus lourd que les mots. Une enseignante prisonnière d’un mariage aux failles invisibles, une adolescente rejetée par tous depuis un scandale qui continue de la poursuivre, un professeur admiré dont la bienveillance cache peut-être d’autres vérités… Chacun avance avec ses blessures, ses mensonges et ses obsessions, jusqu’au jour où les frontières entre innocence et culpabilité se brouillent. Dans cette mécanique implacable où chaque regard peut condamner et chaque secret devenir une arme, les certitudes s’effondrent une à une, laissant place à une vérité aussi inattendue que vertigineuse.' where id = 10;

-- Les heures fragiles
update public.books set summary = 'Diane a toujours eu des rêves simples. Un mari, deux enfants, un métier qui lui plaît, c’est plus que ce qu’elle osait espérer. Le jour où Seb la quitte, son monde vacille. Absorbée par sa peine, elle ne voit pas que le drame se joue ailleurs. Tout près d’elle, dans cette chambre qui fait face à la sienne, les rires de sa fille s’épuisent. Lou a seize ans, le mal de grandir, et son premier chagrin d’amour lui arrache plus que des larmes. Quand Diane comprend, elle est prête à tout pour l’aider. Y compris à retourner vers un passé qu’elle avait fui. Ensemble, mère et fille marchent sur un fil. Sous leurs pas, le torrent de la vie gronde et emporte avec lui les heures fragiles.' where id = 11;

-- Tata
update public.books set summary = 'Palmarès Les 100 livres de l''année 2024 - Lire Magazine " Tata est son livre le plus ambitieux, le plus intime, le plus libérateur, le plus important." Pierre Vavasseur - Le Parisien " Tata est un livre palpitant, surprenant et surtout réussi." Le Parisien " Valérie Perrin s''affirme comme [une] conteuse prodigieuse." Olivia de Lamberterie - Elle « Colette est remorte. Ce mot n''existe nulle part. Remourir, ça n''existe pas. » Colette était une femme sans histoire. C''est du moins ce que l''on croyait jusqu''au jour où sa nièce apprend son décès par un appel de la police. Car Colette, sa tante unique, a déjà été enterrée il y a trois ans... Avec ce roman virtuose où s''entrelacent destins et intrigues palpitantes, Valérie Perrin, extraordinaire conteuse de nos vies, signe son grand retour.' where id = 12;

-- La psy
update public.books set summary = 'Jeunes mariés, Tricia et Ethan recherchent la maison de leurs rêves. Alors qu''ils visitent un manoir isolé ayant appartenu au docteur Adrienne Hale, une psychiatre renommée disparue sans laisser de trace quatre ans plus tôt, une violente tempête de neige les piège sur place. Et la maison n''a rien d''un cocon rassurant... Il y a ces empreintes de pas récentes sur le parquet, ces bruits à l''étage, comme si quelqu''un vivait là. Pire encore : Tricia découvre une pièce secrète qui renferme les enregistrements audio de chaque patient du docteur Hale. La jeune femme les écoute les uns après les autres, tard dans la nuit. La toile de mensonges ayant conduit à la disparition de la psy se dévoile lentement. Mais déterrer de vilains petits secrets est un jeu dangereux, et lorsque Tricia écoute le dernier enregistrement, il est déjà trop tard..[4 ème de couverture]' where id = 13;

-- Quelqu'un d'autre
update public.books set summary = '« Il y a trois vérités : ma vérité, ta vérité, la vérité. » Côte d''Azur - Printemps 2023 Au large de Cannes, un yacht dérive entre les îles de Lérins.À son bord repose Oriana Di Pietro, éditrice italienne et héritière d''une célèbre famille milanaise. Agressée sauvagement, elle succombera après dix jours de coma. Qui a tué Oriana ? Un homme et trois femmes livrent leur version de l''histoire : Adrien, le mari de la victime, pianiste de jazz séduisant et mystérieux ; l''insaisissable Adèle, sa jeune maîtresse ; Justine, la policière locale chargée de l''enquête et Oriana enfin, à travers le récit bouleversant des dernières semaines de sa vie. Personne ne ment. Mais personne n''est d''accord sur la vérité... Fascinant et audacieux, ce suspense psychologique imprévisible s''impose comme l''un des romans les plus réussis de Guillaume Musso. Une histoire exceptionnelle qui ne livre sa vérité qu’à la dernière ligne « LE ROI DU NOIR EUROPÉEN. » La Repubblica, Italie « LE MAÎTRE FRANÇAIS DU SUSPENSE. » The New York Times, États-Unis « UN PHÉNOMÈNE. » El Mundo, Espagne' where id = 14;

-- La femme de ménage
update public.books set summary = 'Chaque jour, Millie fait le ménage dans la belle maison des Winchester, une riche famille new-yorkaise. Elle récupère aussi leur fille à l''école et prépare les repas avant d''aller se coucher dans sa chambre, au grenier. Pour la jeune femme, ce nouveau travail est une chance inespérée. L''occasion de repartir de zéro. Mais, sous des dehors respectables, sa patronne se montre de plus en plus instable et toxique. Et puis il y a aussi cette rumeur dérangeante qui court dans le quartier : madame Winchester aurait tenté de noyer sa fille quelques années auparavant. Heureusement, le gentil et séduisant monsieur Winchester est là pour rendre la situation supportable. Mais le danger se tapit parfois sous des apparences trompeuses. Et lorsque Millie découvre que la porte de sa chambre mansardée ne ferme que de l''extérieur, il est peut-être déjà trop tard...' where id = 15;

-- Celle qui sait
update public.books set summary = 'TOUT LE MONDE EST CONVAINCU QUE LENORA HOPE EST LA TUEUSE. ET VOUS ? Le massacre de la famille Hope, lors d''une nuit sanglante de 1929, a bouleversé les habitants du Maine. Si la plupart des gens sont persuadés que Lenora, dix-sept ans, en est responsable, la police n’a jamais pu le prouver. Après avoir nié à l’époque toute implication, l’intéressée n’a plus quitté Hope’s End, le manoir dressé en bord de falaise où le drame s’est produit. Nous sommes en 1983 lorsque Kit McDeere, aide-soignante à domicile, se présente pour s’occuper de Lenora après la fuite inexpliquée de sa précédente infirmière. Âgée de plus de soixante-dix ans et en fauteuil roulant, Lenora a été rendue muette par une série d’AVC. Elle ne peut communiquer avec Kit que grâce à une vieille machine à écrire. Jusqu’au soir où, de son seul doigt valide, elle commence à taper : je veux tout vous raconter Auteur best-seller, RILEY SAGER a écrit neuf thrillers publiés dans plus de vingt pays. Né en Pennsylvanie, il vit à Princeton, dans le New Jersey. « Un vrai choc. » LISA GARDNER « Des twists à couper le souffle. » SHARI LAPENA « Une lecture d’enfer. » RACHEL HAWKINS « Terrifiant. » KARIN SLAUGHTER' where id = 16;

-- La femme de ménage voit tout
update public.books set summary = '« Je me demande si je n''ai pas commis une terrible erreur en m''installant ici... » . Après avoir été au service des autres en tant que femme de ménage, Millie s''est enfin construit une vie à elle. Elle vient même d''emménager dans une belle maison, dans une petite impasse chic et tranquille, avec son mari et ses deux enfants.. Mais son rêve d''une vie paisible est rapidement terni par la rencontre de ses voisins. Il y a Suzette, bien trop snob et aguicheuse, son insipide mari, mais surtout leur terrifiante femme de ménage au regard perçant et au comportement plus que suspect.. Les craintes de Millie montent d''un cran lorsque des bruits étranges se font entendre la nuit dans sa propre maison. Pire : elle éprouve un étrange malaise et se sent épiée. C''est certain, quelque chose ne tourne pas rond dans cette rue si tranquille. Mais est-elle prête à en découvrir les secrets ? Et surtout, le temps de comprendre ce qui ne va pas, tout peut arriver.... Elle vous observe. Et vous n''avez nulle part où vous cacher. .' where id = 17;

-- Les secrets de la femme de ménage
update public.books set summary = 'C’est une chance inespérée pour Millie d’avoir décroché un nouveau travail. Chez les Garrick, un couple fortuné qui possède un somptueux appartement avec vue sur New York, elle fait le ménage et prépare les repas dans la magnifique cuisine. Cela paraît trop beau pour être vrai. Et effectivement, la femme de ménage ne tarde pas à déceler quelques ombres au tableau... Son patron, Douglas Garrick, est d’humeur de plus en plus changeante. Et pourquoi sa femme Wendy reste-t-elle toujours enfermée dans la chambre d’amis ? Le jour où Millie découvre du sang sur une chemise de nuit, elle ne peut plus rester les bras croisés. Quelque chose se trame dans cette maison. Une situation à laquelle Millie n’est pas préparée et qui pourrait bien se retourner contre elle si elle continue de vouloir découvrir les secrets des autres...' where id = 18;

-- D'autres printemps
update public.books set summary = 'Elles n''imaginent rien de ce qui les attend au bout du chemin, là où l''histoire a commencé. Flora vient de voir son plus grand rêve s''effondrer. Pourtant, quand on l''appelle au chevet de sa grand-mère, elle envoie tout valser pour la retrouver. À son arrivée, Line, quatre-vingt-dix printemps, a une requête des plus surprenantes: Flora doit l''arracher à l''hôpital pour la conduire dans un petit village de Toscane. Pourquoi là-bas? Personne ne lui connaît d''attaches en Italie. Flora hésite, mais Line insiste: c''est sa dernière volonté. Alors, au matin, elles fuguent. Embarquée dans un road trip insolite, Flora ignore la vraie raison de ce voyage et l''ampleur du secret qu''elle s''apprête à découvrir. L''une roule vers son passé, l''autre vers son avenir: grand-mère et petite-fille ont des choses à se dire.' where id = 19;

-- L'homme qui lisait des livres
update public.books set summary = 'Entre les ruines fumantes de Gaza et les pages jaunies des livres, un vieil homme attend. Il attend quoi ? Peut-être que quelqu''un s''arrête enfin pour écouter. Car les livres qu''il tient entre ses mains ne sont pas que des objets – ils sont les fragments d''une vie, les éclats d''une mémoire, les cicatrices d''un peuple. Quand un jeune photographe français pointe son objectif vers ce vieillard entouré de livres, il ignore qu''il s''apprête à traverser le miroir. " N''y a-t-il pas derrière tout regard une histoire ? Celle d''une vie. Celle de tout un peuple, parfois ", murmure le libraire. Commence alors l''odyssée palestinienne d''un homme qui a choisi les mots comme refuge, résistance et patrie. De l''exode à la prison, des engagements à la désillusion politique, du théâtre aux amours, des enfants qu''on voit grandir et vivre, aux drames qui vous arrachent ceux que vous aimez, sa voix nous guide à travers les labyrinthes de l''Histoire et de l''intime. Dans un monde où les bombes tentent d''avoir le dernier mot, il nous rappelle que les livres sont notre plus grande chance de survie – non pour fuir le réel, mais pour l''habiter pleinement. Comme si, au milieu du chaos, un homme qui lit était la plus radicale des révolutions.' where id = 20;

-- L'invitée surprise
update public.books set summary = '«Vous êtes donc venue ici pour mettre fin à vos jours en ingurgitant des analgésiques pour chat... — Pas n’importe lesquels. Ceux de mon chat. — ... et vous vous retrouvez au milieu d’un mariage? — Oui.» Après y avoir pensé pendant des années, Phoebe arrive enfin au Cornwall Inn, un luxueux hôtel du XIXe siècle sur la falaise de Newport, dans le Rhode Island. Elle a toujours rêvé d’y séjourner avec son mari, déguster des huîtres et faire des promenades en bateau au coucher du soleil. Malheureusement, elle s’y rend seule, sans bagages, dans sa plus belle robe en soie verte, déterminée à s’offrir une dernière folie avant de mettre fin à ses jours. Car après plusieurs fausses couches et le départ de son mari, Phoebe n’a plus envie de continuer. Elle qui croyait avoir prévu chaque détail ne s’attendait pas à se retrouver au beau milieu du mariage d’une exubérante future mariée... «Avec humour et tendresse, Alison Espach nous livre tout l’éventail d’émotions qui accompagne le mariage et l’engagement de toute une vie.» The New York Times' where id = 21;

-- La Petite bonne
update public.books set summary = 'Domestique au service des bourgeois, elle est travailleuse, courageuse, dévouée. Mais ce week-end-là, elle redoute de se rendre chez les Daniel. Exceptionnellement, Madame a accepté d''aller prendre l''air à la campagne. Alors la petite bonne devra rester seule avec Monsieur, un ancien pianiste accablé d''amertume, gueule cassée de la bataille de la Somme. Il faudra cohabiter, le laver, le nourrir. Mais Monsieur a un autre projet en tête. Un plan irrévocable, sidérant. Et si elle acceptait ? Et si elle le défiait ? Et s''ils se surprenaient ?' where id = 22;

-- Le Barman du Ritz
update public.books set summary = 'Paris, pendant la Seconde Guerre mondiale. Alors que la ville est occupée, un seul palace demeure ouvert, le Ritz qui devient le quartier général de la Luftwaffe. Entre ses murs, se croisent et se côtoient les hommes de la Gestapo, des célébrités, des résistants et des profiteurs de guerre sous le regard acéré de Frank Meier, le barman, émigré autrichien d''origine juive. Premier roman.' where id = 24;

-- Les Habitantes
update public.books set summary = 'L’histoire se déroule entre la fin du printemps et celle de l’été, dans un hameau et ses alentours, au cœur de collines couvertes de forêts, de champs et de routes. Emily vit seule avec sa chienne Loyse dans la maison héritée de sa grand-mère. C’est là qu’elle a grandi, quand son père est parti fonder une nouvelle famille. Elle y mène une existence en marge, rythmée par les promenades rituelles, les baignades à l’étang, le travail chez Aude dans la ferme voisine. Un jour, des lettres arrivent, lui signifiant la mise en vente imminente de la maison. Pauline Peyrade est écrivaine. En 2023, elle publie L’Âge de détruire, qui reçoit le prix Goncourt du premier roman. Dans Les Habitantes, chiennes, hirondelles, abeilles, héron, peuplier tremble, champs de chanvres, qu’ils agissent ou non sur les événements de l’histoire, occupent le même plan que les personnages et participent à leur quête.' where id = 25;

-- Les saules
update public.books set summary = 'Â pre et bouleversante, une histoire de liberté et de meurtre, de silence et d’amitié, au cœur d’un hameau breton. Allongée au bord de la rivière, cachée par les saules pleureurs, Marie, dix-sept ans, semble paisible, endormie, ce que démentent les marques sombres sur son cou. Sa mort brutale ébranle toute la communauté, et surtout Marguerite, ...' where id = 27;

-- Mortelle Adèle Tome 23 - Nazebrocadabra !
update public.books set summary = 'L''héroïne N°1 de la bande dessinée jeunesse revient dans un 23e tome de gags toujours aussi attendu du public ! Plus de 70 gags pleins d''énergie et de réflexions sur le quotidien, comme Antoine Dole alias Mr Tan en a le secret, et toujours illustrée par la talentueuse Diane Le Feyer ! © Mr Tan et Diane Le Feyer d''après l''œuvre créée par Mr Tan et Miss Prickly © Mr Tan & Co' where id = 28;

-- Tout le monde aime Clara
update public.books set summary = 'Vous avez lu le Tri Sélectif des Ordures ? Vous avez aimé ? Sur cette belle terre bleue comme une orange d’Eluard, il n’y a pas que des ordures. Il n’y a pas que les hommes qui se comportent comme des ordures et qui méritent un tri sélectif, certaines femmes aussi. Le fait sur lequel on peut se mettre d’accord, c’est qu’il y a bien plus d’hommes qui agissent comme des ordures. Mais les pires de ces femmes sont parfois celles qui se prétendent victimes. Il est temps de leur rendre justice. Certaines qui se prétendent victimes le crient haut et fort : la parole des femmes est sacrée. Tu parles. Même le ministre qui a aboli la peine de mort n’est pas d’accord. La parole des femmes n’est pas plus sacrée que celle des hommes. Ni la vérité, ni le mensonge, ni l’intérêt, ni la perversité n’ont de sexe. Ni même d’âge... Ce roman décrit néanmoins la complexité des situations et le fait que le présent est toujours la conséquence du passé.' where id = 30;

-- Un avenir radieux
update public.books set summary = '« Je viens sauver quelqu’un, se répétait-il, et maintenant qu’il se trouvait à deux heures de Prague, il sentait monter en lui une vive anxiété. » Une échappée belle de Paris à Prague, d’un studio de radio à des ruelles hostiles, d’un cachot glacé à une académie de billard, d’une école de bonnes sœurs aux bureaux obscurs de la République. Chacun des Pelletier, à son heure, devra choisir entre son intérêt et son devoir, et pour certains entre la raison du cœur et la raison d’État. Un dilemme parfois déchirant, sauf pour le chat Joseph, qui lui a choisi depuis longtemps. Passionnant, intense, bouleversant. Un grand roman de Pierre Lemaitre.' where id = 31;

-- Un jour sans femme
update public.books set summary = 'Islande. À la mort de sa meilleure amie, tuée par son compagnon, Katla se lance un défi inédit : organiser une grève des femmes dans le monde entier, pour dénoncer les violences et les inégalités. Japon. Michiko, jeune salariée enceinte, est harcelée par son patron. Salvador. Ana María, ouvrière à l''usine, se bat pour sa fille, condamnée à trente ans de prison pour suspicion d''avortement. Sénégal. Hawa, urgentiste, tente de sauver une enfant quand le trauma de son passé ressurgit. Katla, Michiko, Ana María et Hawa ne se connaissent pas, mais toutes décident de dire non. Elles étaient seules, elles seront des millions. Sans les femmes, le monde s''arrêtera-t-il de tourner ? Et s''il suffisait d''un jour pour tout changer ?' where id = 32;

-- Une unique lueur
update public.books set summary = '- Vous avez regardé les photos, Danglard ? De la scène du crime ? demanda Adamsberg. - Cela va de soi. - Et donc ? Cela vous dit quelque chose ? Parce qu''à moi, oui. - Tiens. Et cela vous raconte quoi ? - Mais justement, rien. C''est quelque chose que je ne sais pas alors que cela me dit quelque chose. Donc ? - Aucune idée. - Faites un effort, nom d''un chien. - Désolé, commissaire, dit Danglard avec une pointe d''indifférence. - Bien. Réunion plénière dans quinze minutes. Il nous faut comprendre. - Comprendre quoi ? - Mais le quelque chose, commandant. On commence par là' where id = 33;

-- J'ai dû rêver trop fort
update public.books set summary = 'Les plus belles histoires d''amour ne meurent jamais. Les plus belles histoires d''amour ne meurent jamais. Elles continuent de vivre dans nos souvenirs et les coïncidences cruelles que notre esprit invente. Mais quand, pour Nathy, ces coïncidences deviennent trop nombreuses, doit-elle croire qu''il n''y a pas de hasard, seulement des rendez-vous ? Qui s''évertue à lui faire revivre cette parenthèse passionnelle qui a failli balayer sa vie ? Quand passé et présent se répètent au point de défier toute explication rationnelle, Nathy doit-elle admettre qu''on peut remonter le temps ? En quatre escales, Montréal, San Diego, Barcelone et Jakarta, dans un jeu de miroirs entre 1999 et 2019, J''ai dû rêver trop fort déploie une partition virtuose, mêlant passion et suspense, au plus près des cœurs qui battent trop fort.' where id = 44;

-- Les 7 habitudes de ceux qui réalisent tout ce qu'ils entreprennent
update public.books set summary = 'Appliquez les principes du best seller international Les 7 Habitudes des gens efficaces grâce à son journal de bord et gagnez en productivité. Votre gestion du temps n’est pas satisfaisante et cela impacte votre productivité et votre réussite ? Que vous ayez du mal à atteindre vos objectifs ou que vous soyez à la recherche de nouvelles habitudes performantes, Les 7 habitudes des gens efficaces vous fournira toutes les méthodes à mettre en application et vous guidera vers la réussite. Atteignez facilement tous vos objectifs. Les 7 Habitudes des gens efficaces est l’un des livres les plus inspirants jamais écrits et a changé la vie de nombreux lecteurs. Découvrez dès à présent sa version journal qui vous donnera la possibilité de transformer vos visions en actions concrètes. Son format concis est accessible et facile à suivre. Chaque habitude est transformée en objectifs hebdomadaires, vous permettant ainsi de gagner en motivation, prendre confiance en vous et stimuler votre réussite personnelle. Cultivez le succès et l’épanouissement personnel. Ce journal vous livrera les clés du succès grâce à ses cas pratiques, ses exercices et ses citations inspirantes. Apprenez à développer votre réflexion, gérer le temps et être efficace pour atteindre tous vos objectifs. Dans ce journal, vous trouverez: • Des citations inspirantes de développement personnel vous permettant de renforcer la confiance et l’estime de soi. • Des méthodes et cas pratiques pour une gestion du temps optimale. • Des conseils, des exercices et des défis motivants pour gagner en productivité, être organisé, gérer son stress et atteindre ses objectifs. Si vous avez aimé les livres tels que Les 7 Habitudes des gens qui réalisent tout ce qu’ils entreprennent, Atomic Habits, ou le Pouvoir des Habitudes, alors Les 7 Habitudes des Gens Efficaces sera votre prochaine lecture.' where id = 48;

-- J'ai dû rêver trop fort
update public.books set summary = 'Les plus belles histoires d''amour ne meurent jamais. Les plus belles histoires d''amour ne meurent jamais. Elles continuent de vivre dans nos souvenirs et les coïncidences cruelles que notre esprit invente. Mais quand, pour Nathy, ces coïncidences deviennent trop nombreuses, doit-elle croire qu''il n''y a pas de hasard, seulement des rendez-vous ? Qui s''évertue à lui faire revivre cette parenthèse passionnelle qui a failli balayer sa vie ? Quand passé et présent se répètent au point de défier toute explication rationnelle, Nathy doit-elle admettre qu''on peut remonter le temps ? En quatre escales, Montréal, San Diego, Barcelone et Jakarta, dans un jeu de miroirs entre 1999 et 2019, J''ai dû rêver trop fort déploie une partition virtuose, mêlant passion et suspense, au plus près des cœurs qui battent trop fort.' where id = 58;

